services:
  postgres:
    image: postgres:16-alpine
    container_name: college_sms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: college_admin
      POSTGRES_PASSWORD: college_password
      POSTGRES_DB: college_sms
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
